---
title: "LRF municípios catarinenses "
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: https://github.com/andreferraribr/lrf
    social: [ "twitter", "facebook", "menu" ]
runtime : shiny  
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(httr)
library(tidyverse)
library(readxl)
library(DT)
library(plotly)
library(leaflet)
library(brazilmaps)
library(shinyWidgets)
library(shiny)
library(sf)
library(vroom)
library(spdplyr)
library(htmltools)
```

```{r}
rreo <- read_csv("rreo_uf_lrf_invest.csv")

rgf <- read_csv("rgf_uf.csv")
```


```{r}



pessoal_df<- rgf %>% filter(startsWith(rgf$coluna, "%"), periodo > 1,conta =="Despesa Total com Pessoal - DTP", (startsWith (rgf$instituicao, "Governo do"))) %>% group_by(instituicao, uf, exercicio, coluna, conta, periodo, periodicidade)  %>% summarise(valor = valor)

dcl_df<- rgf %>% filter(coluna == "Até o 3º Quadrimestre", conta == "% da DCL sobre a RCL (III/RCL)",(startsWith (rgf$instituicao, "Governo do"))) %>% group_by(instituicao, uf, exercicio, coluna, conta, periodo, periodicidade)   %>% summarise(valor = valor)

invest_df<- rreo %>% filter%>% filter(startsWith (rreo$conta, "INVES"), startsWith (rreo$coluna,"DESPESAS PAGAS ATÉ"), !startsWith (rreo$cod_conta,"InvestimentosIntra")) %>% group_by(instituicao, uf, exercicio, coluna, conta, periodo, periodicidade)  %>% summarise(valor = sum(valor))

prev_df<-rreo %>% filter%>% filter(startsWith (rreo$conta, "Resultado Previdenciário"), startsWith (rreo$coluna,"Até o Bimestre")) %>% group_by(instituicao, uf, exercicio, coluna, conta, periodo, periodicidade)  %>% summarise(valor = sum(valor))

prev35_df<-rreo %>% filter%>% filter(startsWith (rreo$conta, "Resultado Previdenciário"), startsWith (rreo$coluna,"35º Exercício")) %>% group_by(instituicao, uf, exercicio, coluna, conta, periodo, periodicidade)  %>% summarise(valor = sum(valor))


```


Row
-----------------------------------------------------------------------



### Despesa Pessoal

```{r, chart 1}

pessoal_uf_df<- pessoal_df %>% filter (uf == "SC")

desp_pessoal_plot <- ggplot(pessoal_df, aes(x=exercicio, y=valor, color="red")) +
  geom_jitter( aes(text=paste("UF: ", uf)), width=0.25, alpha=0.5 ) +
  geom_line(data = pessoal_uf_df, aes(x=exercicio, y=valor, color="black", text=paste("UF: ", uf)), width=0.25, alpha=0.5)+
  geom_point(data = pessoal_uf_df, aes(x=exercicio, y=valor, color="black", text=paste("UF: ", uf)), width=0.25, alpha=0.5)+
  geom_hline(yintercept=49) +
  geom_smooth(method = "lm")+
  theme(axis.text.x = element_text( hjust = 0.1)) +
  labs(title = "série histórica do % de comprometimento da Receita Corrente Líquida das UFs com a Despesa de Pessoal",
       x = "Ano",
       y = "%")+ theme_classic()

(desp_pessoal_plot <- ggplotly(desp_pessoal_plot))


```



### DCL

```{r, DCL}
dcl<- rgf %>% filter(coluna == "Até o 3º Quadrimestre", conta == "% da DCL sobre a RCL (III/RCL)",(startsWith (rgf$instituicao, "Governo do"))) %>% group_by(instituicao, exercicio, conta, periodo, periodicidade)  %>% summarise(limite = valor)

dcl_df<- rgf %>% filter(coluna == "Até o 3º Quadrimestre", conta == "% da DCL sobre a RCL (III/RCL)",(startsWith (rgf$instituicao, "Governo do"))) %>% group_by(instituicao, exercicio, conta, periodo, periodicidade)  %>% summarise(valor = valor)

dcl_plot <- ggplot(dcl,aes(x=exercicio, y=limite, colour=limite)) +
  geom_jitter(aes(text=paste("instituicao: ", instituicao)), width=0.25, alpha=0.5, ) +
  geom_hline(yintercept=200) +
  geom_smooth(method = "lm")+
  theme(axis.text.x = element_text( hjust = 0.1)) +
  labs(title = "UFs: % da DCL sobre a RCL (2015 a 2019)",
       x = "Ano",
       y = "%")+ theme_classic()

(dcl_plot <- ggplotly(dcl_plot)%>% add_trace(y = ~limite, name = 'trace 0',mode = 'lines'))

dcl_plot
```

```{r}
rgf_df<- rbind(pessoal_df,dcl_df)
write_csv(rgf_df,"rgf_df.csv")
```


### Investimento

```{r, investimento}
invest<- rreo %>% filter%>% filter(startsWith (rreo$conta, "INVES"), startsWith (rreo$coluna,"DESPESAS PAGAS ATÉ"), !startsWith (rreo$cod_conta,"InvestimentosIntra")) 

invest_df<- rreo %>% filter%>% filter(startsWith (rreo$conta, "INVES"), startsWith (rreo$coluna,"DESPESAS PAGAS ATÉ"), !startsWith (rreo$cod_conta,"InvestimentosIntra")) %>% group_by(instituicao, exercicio, conta, periodo, periodicidade) %>% summarise(valor = sum(valor))

p <- ggplot(invest,aes(x=exercicio, y=valor, colour=valor)) +
  geom_jitter(aes(text=paste("instituicao: ", instituicao)), width=0.25, alpha=0.5, ) +
  geom_hline(yintercept=200) +
  geom_smooth(method = "lm")+
  theme(axis.text.x = element_text( hjust = 0.1)) +
  labs(title = "Despesa com pessoal",
       x = "Ano",
       y = "%")
fig <- ggplotly(p)%>% add_trace(y = ~valor, name = 'trace 0',mode = 'lines')


fig

```

Row
-----------------------------------------------------------------------

### previdencia

```{r}
prev<- rreo %>% filter%>% filter(startsWith (rreo$conta, "Resultado Previdenciário"), startsWith (rreo$coluna,"Até o Bimestre")) %>% group_by(instituicao, exercicio) %>% summarise(valor = sum(valor))

prev_df<-rreo %>% filter%>% filter(startsWith (rreo$conta, "Resultado Previdenciário"), startsWith (rreo$coluna,"Até o Bimestre")) %>% group_by(instituicao, exercicio, conta, periodo, periodicidade) %>% summarise(valor = sum(valor))


p <- ggplot(prev,aes(x=exercicio, y=valor, colour=valor)) +
  geom_jitter(aes(text=paste("instituicao: ", instituicao)), width=0.25, alpha=0.5, ) +
  geom_hline(yintercept=200) +
  geom_smooth(method = "lm")+
  theme(axis.text.x = element_text( hjust = 0.1)) +
  labs(title = "Despesa com pessoal",
       x = "Ano",
       y = "%")
fig <- ggplotly(p)%>% add_trace(y = ~valor, name = 'trace 0',mode = 'lines')


fig


```



### Chart 5

```{r eval=FALSE, include=FALSE}

prev35_df<-rreo %>% filter%>% filter(startsWith (rreo$conta, "Resultado Previdenciário"), startsWith (rreo$coluna,"35º Exercício")) %>% group_by(instituicao, exercicio, conta, periodo, periodicidade) %>% summarise(valor = sum(valor))

%>% 

p <- ggplot(limites,aes(x=exercicio, y=limite, colour=limite)) +
  geom_jitter(aes(text=paste("instituicao: ", instituicao)), width=0.25, alpha=0.5, ) +
  geom_hline(yintercept=55) +
  geom_hline(yintercept=60)+
  geom_smooth(method = "lm")+
  theme(axis.text.x = element_text( hjust = 0.1)) +
  labs(title = "Despesa com pessoal",
       x = "Ano",
       y = "%")
fig <- ggplotly(p)%>% add_trace(y = ~limite, name = 'trace 0',mode = 'lines')


fig
```


```{r}
rreo_df<- rbind(invest_df, prev_df, prev35_df)

write_csv(rreo_df,"rreo_df.csv")

data_lrf<- rbind (rreo_df, rgf_df)

write_csv(data_lrf,"data_lrf.csv")
```


### Chart 6

```{r eval=FALSE, include=FALSE}
divida<- rgf %>% filter(startsWith(rgf$coluna, "%"), periodo > 1, (startsWith (rgf$conta, "Dí"))) %>% group_by(instituicao, exercicio, conta, periodo, periodicidade)  %>% summarise(limite = valor)

divida <- divida %>% mutate(divida = case_when(limite < -100 ~ -100, 
                                               limite > 250 ~ 250,
                                               TRUE ~ limite))

p <- ggplot(divida,aes(x=exercicio, y=divida, colour=divida)) +
  geom_jitter(aes(text=paste("instituicao: ", instituicao)), width=0.25, alpha=0.5, ) +
  geom_hline(yintercept=200) +
  geom_smooth(method = "lm")+
  theme(axis.text.x = element_text( hjust = 0.1)) +
  labs(title = "Despesa com pessoal",
       x = "Ano",
       y = "%")
  
fig <- ggplotly(p)%>% add_trace(y = ~divida, name = 'trace 0',mode = 'lines')


fig

```
